services:
  test-dotnet-queue-subscriber-core-tests:
    build:
      target: development
    image: test-dotnet-queue-subscriber-core-tests-development
    container_name: test-dotnet-queue-subscriber-core-tests
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet watch --project test/Test.Dotnet.Queue.Subscriber.Core.Tests/Test.Dotnet.Queue.Subscriber.Core.Tests.csproj test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./src/Test.Dotnet.Queue.Subscriber.Core:/home/dotnet/src/Test.Dotnet.Queue.Subscriber.Core
      - ./test/Test.Dotnet.Queue.Subscriber.Core.Tests:/home/dotnet/test/Test.Dotnet.Queue.Subscriber.Core.Tests
      - ./test-output:/home/dotnet/Test.Dotnet.Queue.Subscriber.Core.Tests/test-output

  test-dotnet-queue-subscriber-api-tests:
    build:
      target: development
    image: test-dotnet-queue-subscriber-api-tests-development
    container_name: test-dotnet-queue-subscriber-api-tests
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet watch --project test/Test.Dotnet.Queue.Subscriber.Api.Tests/Test.Dotnet.Queue.Subscriber.Api.Tests.csproj test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./src/Test.Dotnet.Queue.Subscriber.Api:/home/dotnet/src/Test.Dotnet.Queue.Subscriber.Api
      - ./test/Test.Dotnet.Queue.Subscriber.Api.Tests:/home/dotnet/test/Test.Dotnet.Queue.Subscriber.Api.Tests
      - ./test-output:/home/dotnet/Test.Dotnet.Queue.Subscriber.Api.Tests/test-output